spring:
  application:
    name: library

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml

library:
  fine:
    rates:
      STANDARD:
        daily-rate: 1000
        grace-days: 0
      STUDENT:
        daily-rate: 500
        grace-days: 1
      PREMIUM:
        daily-rate: 0
        grace-days: 3
    max-fine-cap-enabled: true

  loan:
    period-days: 14
    extension-days: 7
    max-extensions: 1
    max-books-per-member: 5
    max-unpaid-threshold: 15000

  reservation:
    notification-expiry-days: 3

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    liquibase: INFO